### PR TITLE
Share File

### PR DESCRIPTION
**Pull request by nielscup**
I have added functionality to share files (images, pdfs, etc), both local and remote files. I have only implemented iOS and Android. Just run either the iOS or the Android Test project and click the "Share file" button.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Is there an API on Windows at all to do it? Just curious, we can specify in the docs that it only is an iOS/Android API.

**Comment by nielscup** [comment]
Good question, I will probably be needing it in a couple of months so I will dive into it then.

**Comment by jamesmontemagno** [comment]
So there are a few things here now reading through the code:

1.) For Android we would have to implement Permissions since read/write external is now 
2.) These permissions should be added to the assembly
3.) If we don't support Windows platforms then they shouldnt' throw unless we implement a few properties on the interface called "SupportsLocalFileShare" & "SupportRemoteFileShare" else devs could get into trouble using the API
4.) Instead of WebClient could we just use HttpClient as it is a newer implementation and is better IMHO
5.) I would refactor your interface to be "Task<ShareStatus>" where it has a success boolean and a error exception and then get rid of the actual Error event as that is not a great way of handling situation. Else, just let it bubble up.

**Comment by nielscup** [comment]
Sorry for the late response. This is my first time working on a Xamarin plugin, so I will have to dive in a little deeper. But I am a little busy right now so I will look at this later. ps: feel free to change it as you like.

**Pull request closed without merging**
